package theme

import "github.com/charmbracelet/lipgloss"

var (
	SumiInk0      = lipgloss.Color("#16161D")
	SumiInk1      = lipgloss.Color("#1F1F28")
	SumiInk2      = lipgloss.Color("#2A2A37")
	SumiInk3      = lipgloss.Color("#363646")
	SumiInk4      = lipgloss.Color("#54546D")
	WaveBlue1     = lipgloss.Color("#223249")
	WaveBlue2     = lipgloss.Color("#2D4F67")
	WinterGreen   = lipgloss.Color("#2B3328")
	WinterYellow  = lipgloss.Color("#49443C")
	WinterRed     = lipgloss.Color("#43242B")
	WinterBlue    = lipgloss.Color("#252535")
	AutumnGreen   = lipgloss.Color("#76946A")
	AutumnRed     = lipgloss.Color("#C34043")
	AutumnYellow  = lipgloss.Color("#DCA561")
	SamuraiRed    = lipgloss.Color("#E82424")
	RoninYellow   = lipgloss.Color("#FF9E3B")
	WaveAqua1     = lipgloss.Color("#6A9589")
	DragonBlue    = lipgloss.Color("#658594")
	FujiWhite     = lipgloss.Color("#DCD7BA")
	OldWhite      = lipgloss.Color("#C8C093")
	SpringViolet1 = lipgloss.Color("#938AA9")
	OniViolet     = lipgloss.Color("#957FB8")
	CrystalBlue   = lipgloss.Color("#7E9CD8")
	SpringViolet2 = lipgloss.Color("#9CABCA")
	SpringBlue    = lipgloss.Color("#7FB4CA")
	LightBlue     = lipgloss.Color("#A3D4D5")
	WaveAqua2     = lipgloss.Color("#7AA89F")
	SpringGreen   = lipgloss.Color("#98BB6C")
	BoatYellow1   = lipgloss.Color("#938056")
	BoatYellow2   = lipgloss.Color("#C0A36E")
	CarpYellow    = lipgloss.Color("#E6C384")
	SakuraPink    = lipgloss.Color("#D27E99")
	WaveRed       = lipgloss.Color("#E46876")
	PeachRed      = lipgloss.Color("#FF5D62")
	SurimiOrange  = lipgloss.Color("#FFA066")
	KatanaGray    = lipgloss.Color("#717C7C")
	FujiGray      = lipgloss.Color("#727169")
)
